### ISSUE TITLE
Add rules

### ISSUE THREAD

**Issue by Nandhini-Madan** [Alexander01000/pig-game#9]
hi,

Nice project. Add the rules of "how to play" on the home page or in the side of the project.

**Comment by Alexander01000** [comment]
Hi there :wave: 

Thanks for reviewing my project and also for recommending about rules panel. I started working on it! I had a plan on how to implement it but I am still not that good in javascript but I'm gonna give it a shot!

**Comment by mastercodermerwin** [comment]
> hi,
> 
> Nice project. Add the rules of "how to play" on the home page or in the side of the project.

Yeah Weres the rules ???? Alox....

**Comment by Alexander01000** [comment]
Yeah, I'm just thinking about design i.e where should I place the rules panel. I need a little bit of time to think about it more consciously. Thanks for reaching out.

**Comment by Alexander01000** [comment]
hey coders :wave: 

I added rules to the game, and thinking a lot about design and other things I came to conclusion and implemented it! In my opinion, it seems pretty good there but if you see anything odd or have any doubt/questions then let me know in issues, either continue chatting in this `Add rules` issue thread or you can start a new one! Everyone is welcome :smile:
